# adding two vectors in python using numpy... 
# from numpy import array...
from numpy import array

# value for vector... 
v = array([3, 2])

# value for vector... 
w = array([2, -1])

# define formula for add two vectors... 
v_plus_w = v + w

# prints sum of vectors... 
print(v_plus_w)