# how to calculate determinant in python?
# import det from numpy.linalg...
from numpy.linalg import det

# import array from numpy... 
from numpy import array

# declare i-hat1... 
i_hat = array([3, 0])

# declare j-hat1...
j_hat = array([0, 2])

# basis named variable...
basis = array([i_hat, j_hat]).transpose()

# derive determinant with module det...
determinant = det(basis)

# prints determinant...
print(determinant)

# a determinant for a shear...
# import det from numpy.linalg...
from numpy.linalg import det

# import array from numpy... 
from numpy import array

# declare i-hat1... 
i_hat = array([1, 0])

# declare j-hat1...
j_hat = array([1, 1])

# basis named variable...
basis = array([i_hat, j_hat]).transpose()

# derive determinant with module det...
determinant = det(basis)

# prints determinant...
print(determinant)

# a negative determinant...
# import det from numpy.linalg...
from numpy.linalg import det

# import array from numpy... 
from numpy import array

# declare i-hat1... 
i_hat = array([-2, 1])

# declare j-hat1...
j_hat = array([1, 2])

# basis named variable...
basis = array([i_hat, j_hat]).transpose()

# derive determinant with module det...
determinant = det(basis)

# prints determinant...
print(determinant)

# a determinant of zero...
# import det from numpy.linalg...
from numpy.linalg import det

# import array from numpy... 
from numpy import array

# declare i-hat1... 
i_hat = array([-2, 1])

# declare j-hat1...
j_hat = array([3, -1.5])

# basis named variable...
basis = array([i_hat, j_hat]).transpose()

# derive determinant with module det...
determinant = det(basis)

# prints determinant...
print(determinant)

