# a more complicated transformation...
# import array from numpy... 
from numpy import array

# TRANSFORMATION 1... 
# declare i-hat1... 
i_hat1 = array([0, 1])

# declare j-hat1...
j_hat1 = array([-1, 0])

# transform1 named variable...
transform1 = array([i_hat1, j_hat1]).transpose()

# TRANSFORMATION 2...
# declare i-hat2... 
i_hat2 = array([1, 0])

# declare j-hat2...
j_hat2 = array([1, 1])

# transform2 named variable...
transform2 = array([i_hat2, j_hat2]).transpose()

# combine transformations... 
# using @ operator for combining two different transformations...
combined = transform2 @ transform1

# TEST...
print("COMBINED MATRIX: \n {}".format(combined))

# define vector...
v = array([1, 2])

# prints combined transformation...
print(combined.dot(v))

# applying transformation in reverse... 
# import array from numpy... 
from numpy import array

# TRANSFORMATION 1... 
# declare i-hat1... 
i_hat1 = array([0, 1])

# declare j-hat1...
j_hat1 = array([-1, 0])

# transform1 named variable...
transform1 = array([i_hat1, j_hat1]).transpose()

# TRANSFORMATION 2...
# declare i-hat2... 
i_hat2 = array([1, 0])

# declare j-hat2...
j_hat2 = array([1, 1])

# transform2 named variable...
transform2 = array([i_hat2, j_hat2]).transpose()

# combine transformations... 
# using @ operator for combining two different transformations...
combined = transform1 @ transform2

# TEST...
print("COMBINED MATRIX: \n {}".format(combined))

# define vector...
v = array([1, 2])

# prints combined transformation...
print(combined.dot(v))

# Using dot() Versus matmul() and @... 
rotated = transform1.dot(v)
sheered = transform2.dot(rotated)
print("SHEERED: \n" ,(sheered))