# matrix vector multiplication in numpy...
# importing array from numpy... 
from numpy import array 

# compose basic matrix with i-hat and j-hat... 
basis = array([[3, 0], [0, 2]])

# declear vector as v... 
v = array([1, 1])

# creats new vector... 
# by transforming v with dot product...
new_v = basis.dot(v)

# prints new vector... 
print(new_v)

# seperating the basis vector and applying them as transformation...
# importing array from numpy... 
from numpy import array 

# declare i-hat... 
i_hat = array([2, 0])

# declare j-hat...
j_hat = array([0, 3])

# compose basic matrix using i-hat and j-hat...
# also need to transpose rows into colums...
basis = array([i_hat, j_hat]).transpose()

# declear vector v... 
v = array([1, 1])

# create a new vector... 
# by transforming v with dot product... 
new_v = basis.dot(v)

# prints new vector... 
print(new_v)

# transforming a vector using numpy... 
# importing array from numpy... 
from numpy import array 

# declare i-hat... 
i_hat = array([2, 0])

# declare j-hat...
j_hat = array([0, 3])

# compose basic matrix using i-hat and j-hat...
# also need to transpose rows into colums...
basis = array([i_hat, j_hat]).transpose()

# declear vector v 0... 
v = array([2, 1])

# create a new vector... 
# by transforming v with dot product... 
new_v = basis.dot(v)

# prints new vector... 
print(new_v)

# a more complicated transformation...
# importing array from numpy... 
from numpy import array 

# declare i-hat... 
i_hat = array([2, 3])

# declare j-hat...
j_hat = array([2, -1])

# compose basic matrix using i-hat and j-hat...
# also need to transpose rows into colums...
basis = array([i_hat, j_hat]).transpose()

# declear vector v 0... 
v = array([2, 1])

# create a new vector... 
# by transforming v with dot product... 
new_v = basis.dot(v)

# prints new vector... 
print(new_v)